INSERT INTO CUSTOMER (ID, NAME, EMAIL, TYPE, STATUS, CREATED_AT, UPDATED_AT)
VALUES
    (RANDOM_UUID(), 'Leslie Knope', 'leslie.knope@pawnee.gov', 'COMMUNITY_MEMBER', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (RANDOM_UUID(), 'Ron Swanson', 'ron.swanson@pawnee.gov', 'COMMUNITY_MEMBER', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (RANDOM_UUID(), 'JJ''s Diner', 'contact@jjsdiner.com', 'BUSINESS', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (RANDOM_UUID(), 'Some Vendor', 'tom@somevendor.com', 'VENDOR', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (RANDOM_UUID(), 'Sweetums', 'info@sweetums.com', 'BUSINESS', 'INACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
